deploy backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -337,43 +337,88 @@ jobs:
       
       # Here's where you will add some code to rollback on failure  
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  smoke-test:
+    docker:
+          - image: python:3.7-alpine3.11  
+      # Lightweight Docker image 
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl nodejs npm
+            pip install awscli
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 --region us-east-1 describe-instances \
+                      --filters Name=instance-state-name,Values=running Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID} \
+                      --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                      --output text)
+            echo BACKEND_URL: http://${BACKEND_IP}:3030/api/status
+            # your code here
+      - run:
+          name: Backend smoke test.
+          command: |
+            export BACKEND_IP=$(aws ec2 --region us-east-1 describe-instances \
+                     --filters Name=instance-state-name,Values=running Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID} \
+                     --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                     --output text)
+            echo $BACKEND_IP
+            if 
+               curl -s http://${BACKEND_IP}:3030/api/status | grep "ok"
+            then
+               exit 0
+            else
+               exit 1
+            fi
+            # your code here
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com/#/employees | grep "Welcome"
+            then
+                return 0
+            else
+                return 1
+            fi
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  cloudfront-update:
+    docker:
+            - image: amazon/aws-cli
+      # Docker image here that supports AWS CLI
+    steps:
+      - checkout
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            yum install -y tar gzip curl
+            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+            yum install -y nodejs
+            # your code here
+      - run:
+          name: find old env
+          command: |
+             aws cloudformation \
+                	   list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                	    --no-paginate --output text >> old_id.txt
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/old_id.txt
+      - run:
+          name: Update cloudfront distribution
+          command: |
+              aws cloudformation update-stack --use-previous-template --stack-name udapeople \
+                     --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID},UsePreviousValue=false
+      - revert-migrations:
+          ID: ${CIRCLE_WORKFLOW_ID}# Here's where you will add some code to rollback on failure  
 
 # cleanup:
 #     docker:
@@ -430,8 +475,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
